# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20100121032928) do

  create_table "big_string_array_messages", :force => true do |t|
    t.text     "data_1"
    t.text     "data_2"
    t.text     "data_3"
    t.text     "data_4"
    t.text     "data_5"
    t.text     "data_6"
    t.text     "data_7"
    t.text     "data_8"
    t.text     "data_9"
    t.text     "data_10"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "big_string_big_array_messages", :force => true do |t|
    t.text     "data_1"
    t.text     "data_2"
    t.text     "data_3"
    t.text     "data_4"
    t.text     "data_5"
    t.text     "data_6"
    t.text     "data_7"
    t.text     "data_8"
    t.text     "data_9"
    t.text     "data_10"
    t.text     "data_11"
    t.text     "data_12"
    t.text     "data_13"
    t.text     "data_14"
    t.text     "data_15"
    t.text     "data_16"
    t.text     "data_17"
    t.text     "data_18"
    t.text     "data_19"
    t.text     "data_20"
    t.text     "data_21"
    t.text     "data_22"
    t.text     "data_23"
    t.text     "data_24"
    t.text     "data_25"
    t.text     "data_26"
    t.text     "data_27"
    t.text     "data_28"
    t.text     "data_29"
    t.text     "data_30"
    t.text     "data_31"
    t.text     "data_32"
    t.text     "data_33"
    t.text     "data_34"
    t.text     "data_35"
    t.text     "data_36"
    t.text     "data_37"
    t.text     "data_38"
    t.text     "data_39"
    t.text     "data_40"
    t.text     "data_41"
    t.text     "data_42"
    t.text     "data_43"
    t.text     "data_44"
    t.text     "data_45"
    t.text     "data_46"
    t.text     "data_47"
    t.text     "data_48"
    t.text     "data_49"
    t.text     "data_50"
    t.text     "data_51"
    t.text     "data_52"
    t.text     "data_53"
    t.text     "data_54"
    t.text     "data_55"
    t.text     "data_56"
    t.text     "data_57"
    t.text     "data_58"
    t.text     "data_59"
    t.text     "data_60"
    t.text     "data_61"
    t.text     "data_62"
    t.text     "data_63"
    t.text     "data_64"
    t.text     "data_65"
    t.text     "data_66"
    t.text     "data_67"
    t.text     "data_68"
    t.text     "data_69"
    t.text     "data_70"
    t.text     "data_71"
    t.text     "data_72"
    t.text     "data_73"
    t.text     "data_74"
    t.text     "data_75"
    t.text     "data_76"
    t.text     "data_77"
    t.text     "data_78"
    t.text     "data_79"
    t.text     "data_80"
    t.text     "data_81"
    t.text     "data_82"
    t.text     "data_83"
    t.text     "data_84"
    t.text     "data_85"
    t.text     "data_86"
    t.text     "data_87"
    t.text     "data_88"
    t.text     "data_89"
    t.text     "data_90"
    t.text     "data_91"
    t.text     "data_92"
    t.text     "data_93"
    t.text     "data_94"
    t.text     "data_95"
    t.text     "data_96"
    t.text     "data_97"
    t.text     "data_98"
    t.text     "data_99"
    t.text     "data_100"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "big_string_messages", :force => true do |t|
    t.text     "data"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "scalar_array_messages", :force => true do |t|
    t.integer  "data_1"
    t.integer  "data_2"
    t.integer  "data_3"
    t.integer  "data_4"
    t.integer  "data_5"
    t.integer  "data_6"
    t.integer  "data_7"
    t.integer  "data_8"
    t.integer  "data_9"
    t.integer  "data_10"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "scalar_big_array_messages", :force => true do |t|
    t.integer  "data_1"
    t.integer  "data_2"
    t.integer  "data_3"
    t.integer  "data_4"
    t.integer  "data_5"
    t.integer  "data_6"
    t.integer  "data_7"
    t.integer  "data_8"
    t.integer  "data_9"
    t.integer  "data_10"
    t.integer  "data_11"
    t.integer  "data_12"
    t.integer  "data_13"
    t.integer  "data_14"
    t.integer  "data_15"
    t.integer  "data_16"
    t.integer  "data_17"
    t.integer  "data_18"
    t.integer  "data_19"
    t.integer  "data_20"
    t.integer  "data_21"
    t.integer  "data_22"
    t.integer  "data_23"
    t.integer  "data_24"
    t.integer  "data_25"
    t.integer  "data_26"
    t.integer  "data_27"
    t.integer  "data_28"
    t.integer  "data_29"
    t.integer  "data_30"
    t.integer  "data_31"
    t.integer  "data_32"
    t.integer  "data_33"
    t.integer  "data_34"
    t.integer  "data_35"
    t.integer  "data_36"
    t.integer  "data_37"
    t.integer  "data_38"
    t.integer  "data_39"
    t.integer  "data_40"
    t.integer  "data_41"
    t.integer  "data_42"
    t.integer  "data_43"
    t.integer  "data_44"
    t.integer  "data_45"
    t.integer  "data_46"
    t.integer  "data_47"
    t.integer  "data_48"
    t.integer  "data_49"
    t.integer  "data_50"
    t.integer  "data_51"
    t.integer  "data_52"
    t.integer  "data_53"
    t.integer  "data_54"
    t.integer  "data_55"
    t.integer  "data_56"
    t.integer  "data_57"
    t.integer  "data_58"
    t.integer  "data_59"
    t.integer  "data_60"
    t.integer  "data_61"
    t.integer  "data_62"
    t.integer  "data_63"
    t.integer  "data_64"
    t.integer  "data_65"
    t.integer  "data_66"
    t.integer  "data_67"
    t.integer  "data_68"
    t.integer  "data_69"
    t.integer  "data_70"
    t.integer  "data_71"
    t.integer  "data_72"
    t.integer  "data_73"
    t.integer  "data_74"
    t.integer  "data_75"
    t.integer  "data_76"
    t.integer  "data_77"
    t.integer  "data_78"
    t.integer  "data_79"
    t.integer  "data_80"
    t.integer  "data_81"
    t.integer  "data_82"
    t.integer  "data_83"
    t.integer  "data_84"
    t.integer  "data_85"
    t.integer  "data_86"
    t.integer  "data_87"
    t.integer  "data_88"
    t.integer  "data_89"
    t.integer  "data_90"
    t.integer  "data_91"
    t.integer  "data_92"
    t.integer  "data_93"
    t.integer  "data_94"
    t.integer  "data_95"
    t.integer  "data_96"
    t.integer  "data_97"
    t.integer  "data_98"
    t.integer  "data_99"
    t.integer  "data_100"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "scalar_messages", :force => true do |t|
    t.integer  "data"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "string_array_messages", :force => true do |t|
    t.string   "data_1"
    t.string   "data_2"
    t.string   "data_3"
    t.string   "data_4"
    t.string   "data_5"
    t.string   "data_6"
    t.string   "data_7"
    t.string   "data_8"
    t.string   "data_9"
    t.string   "data_10"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "string_big_array_messages", :force => true do |t|
    t.string   "data_1"
    t.string   "data_2"
    t.string   "data_3"
    t.string   "data_4"
    t.string   "data_5"
    t.string   "data_6"
    t.string   "data_7"
    t.string   "data_8"
    t.string   "data_9"
    t.string   "data_10"
    t.string   "data_11"
    t.string   "data_12"
    t.string   "data_13"
    t.string   "data_14"
    t.string   "data_15"
    t.string   "data_16"
    t.string   "data_17"
    t.string   "data_18"
    t.string   "data_19"
    t.string   "data_20"
    t.string   "data_21"
    t.string   "data_22"
    t.string   "data_23"
    t.string   "data_24"
    t.string   "data_25"
    t.string   "data_26"
    t.string   "data_27"
    t.string   "data_28"
    t.string   "data_29"
    t.string   "data_30"
    t.string   "data_31"
    t.string   "data_32"
    t.string   "data_33"
    t.string   "data_34"
    t.string   "data_35"
    t.string   "data_36"
    t.string   "data_37"
    t.string   "data_38"
    t.string   "data_39"
    t.string   "data_40"
    t.string   "data_41"
    t.string   "data_42"
    t.string   "data_43"
    t.string   "data_44"
    t.string   "data_45"
    t.string   "data_46"
    t.string   "data_47"
    t.string   "data_48"
    t.string   "data_49"
    t.string   "data_50"
    t.string   "data_51"
    t.string   "data_52"
    t.string   "data_53"
    t.string   "data_54"
    t.string   "data_55"
    t.string   "data_56"
    t.string   "data_57"
    t.string   "data_58"
    t.string   "data_59"
    t.string   "data_60"
    t.string   "data_61"
    t.string   "data_62"
    t.string   "data_63"
    t.string   "data_64"
    t.string   "data_65"
    t.string   "data_66"
    t.string   "data_67"
    t.string   "data_68"
    t.string   "data_69"
    t.string   "data_70"
    t.string   "data_71"
    t.string   "data_72"
    t.string   "data_73"
    t.string   "data_74"
    t.string   "data_75"
    t.string   "data_76"
    t.string   "data_77"
    t.string   "data_78"
    t.string   "data_79"
    t.string   "data_80"
    t.string   "data_81"
    t.string   "data_82"
    t.string   "data_83"
    t.string   "data_84"
    t.string   "data_85"
    t.string   "data_86"
    t.string   "data_87"
    t.string   "data_88"
    t.string   "data_89"
    t.string   "data_90"
    t.string   "data_91"
    t.string   "data_92"
    t.string   "data_93"
    t.string   "data_94"
    t.string   "data_95"
    t.string   "data_96"
    t.string   "data_97"
    t.string   "data_98"
    t.string   "data_99"
    t.string   "data_100"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "string_messages", :force => true do |t|
    t.string   "data"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
